### ISSUE TITLE
`dev-master@dev` of nieuwe versie taggen..

### ISSUE THREAD

**Issue by bobdenotter** [fruitcake/php-knvb-dataservice-api#4]
Hoi, 

Allereerst: Dank voor het maken van deze package! Superhandig. 

Ik wilde hem gebruiken, en ik liep tegen een paar issues op, die intussen in de `master` branch al verholpen zijn. Ik heb dit nu omzeild door `dev-master@dev` te gebruiken. 

Misschien kun je een nieuwe versie taggen, of `"fruitcakestudio/knvb-dataservice-api": "dev-master@dev"` adviseren in de 'README'?

**Comment by barryvdh** [comment]
Ha,

0.2.1 is tagged!
