### ISSUE TITLE
JsonMapper_Exception: JSON property "PuntenTeam1Verl" must not be NULL

### ISSUE THREAD

**Issue by boyke** [fruitcake/php-knvb-dataservice-api#8]
When retrieving the results from a team this is not an issue, but when doing the same for a competition this error will be thrown.

**Comment by barryvdh** [comment]
Does this fix it for you? https://github.com/fruitcake/php-knvb-dataservice-api/commit/ab69a2c36ac6c1fe6e1786b7c6bc3180adf2bedd

**Comment by boyke** [comment]
Partially, i also did the same for PuntenTeam1Verl, PuntenTeam2Verl, PuntenTeam1Strafsch and PuntenTeam2Strafsch.

This has been changed in version 0.11.0 off the JsonMapper.

Thanks!

**Comment by barryvdh** [comment]
That was already updated here: https://github.com/fruitcake/php-knvb-dataservice-api/commit/bc9b6c0dcb525559ac012c11e1fca43d0a87b6ba
I've tagged a v0.2.2 which includes those fixes.

What has changed in 0.11?

> Fix non-nullable object handling: Exception is now thrown when NULL is given and an object was expected.

These are not objects, right?

**Comment by boyke** [comment]
You're right, seems that i required version 0.2.1 in my composer.json
